### ISSUE TITLE
https://zealot.hu/ergogen returns 404 http code

### ISSUE THREAD

**Issue by beta-tank** [ergogen/ergogen#45]
![image](https://user-images.githubusercontent.com/2918385/141932497-476255c5-88e7-4cc8-88a5-a894dacd0bf4.png)

**Comment by mrzealot** [comment]
Hey, sorry for the inconvenience, but as the project (thankfully!) outgrew being just a subfolder of my personal page, it has now moved to https://ergogen.xyz (with documentation served at https://docs.ergogen.xyz ). We'll try to make the repos/docs/references reflect this change as soon as we can...
