### ISSUE TITLE
Documentation for 4.0

### ISSUE THREAD

**Issue by thoni56** [ergogen/ergogen#88]
As there is some breaking changes in v4, especially around outlines (and probably the other advanced topics, too, I got stuck on outlines), the documentation about that is even more confusing. Since most examples out there are using earlier versions the tip about searching for #ergogen is also not very helpful.

I think a first big help would be to have at least one complete example with outlines, pcb, etc. using the new syntax.

I dug around in the tests and found a completely new list of keywords (`what`, `where`, ... ) which isn't mentioned in the docs. Using those I managed to make a circle and a rectangle, but no success with creating a plate ;-)

**Comment by mrzealot** [comment]
Hey! Your concerns are valid, to say the least. Rest assured that a complete documentation rewrite is underway to address this (preview at https://deploy-preview-12--ergogen.netlify.app/ , but it's mostly just for preprocessing and points for now). Until this matures, your best bet is relying on the community-driven migration guide ( https://github.com/tsteffek/Ergogen-V4-Migration-Guide ). Also, I hear there'll soon be a series of blog posts detailing the creation process of a complete keyboard using ergogen v4, so stay tuned for that as well. Also also, joining our Discord can get you many helpful answers in the meantime, should you get stuck ( http://discord.ergogen.xyz ).
